apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple
spec:
  containers:
  - image: nginx
    name: simple
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: simple
  name: simple-pod2
spec:
  containers:
  - image: nginx
    name: simple-2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}

